spring:
  datasource:
    url: jdbc:mysql://${AWS_RDS_DB_ENDPOINT}:${AWS_RDS_DB_PORT}/${AWS_RDS_DB_NAME}
    username: ${AWS_RDS_DB_MASTER_USERNAME}
    password: ${AWS_RDS_DB_MASTER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true