# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# Referred: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# and https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Java with Maven

on:
  push:
    branches:
      - 'assignmemt4'
      - 'main'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile
      - name: Test with Maven
        run: mvn test
      - name: Package with Maven
        run: mvn -B package --file pom.xml

