# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# Referred: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# and https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Java with Maven

on:
  push:
    branches: [ assignmemt4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile
      - name: Test with Maven
        run: mvn test
      - name: Package with Maven
        run: mvn -B package --file pom.xml

  validate-build-packer:
    runs-on: ubuntu-latest
    name: Validate Packer JSON template
    needs: package_build
    steps:
        - uses: actions/checkout@v2
        - name: Validate Packer Template
          uses: hashicorp/packer-github-actions@master
          with:
            working_directory: 'webapp'
            command: validate
            target: ami.pkr.hcl
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

  packer_build:
        name: Packer AMI Build
        needs: validate-build-packer
        runs-on: ubuntu-latest
        steps:
          #      - name: Download artifacts
          #        uses: actions/download-artifact@v3
          #        with:
          #          name: WebServiceWarFile
          #          path: /home/runner/work/webservice/webservice/ami/WebServiceWarFile.zip

          - uses: actions/checkout@v2
          - name: Packer build
            uses: ExitoLab/packer_build_action_aws@v0.2.10
            with:
              templateFile: 'ami.pkr.hcl'
              workingDir: 'webapp'
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
              AWS_DEFAULT_REGION: us-west-2
