name: Run packer build on a template file

on:
  push:
    branches:
      - 'assignment5'
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  package_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile
      - name: Test with Maven
        run: mvn test
      - name: Maven clean
        run: mvn clean
      - name: Package with Maven
        run: |
          pwd
          ls
          mvn -B package --file pom.xml
          pwd
          cd target
          pwd
          ls -al


  packer_validate:
    runs-on: ubuntu-latest
    name: Validate Packer template
    needs: package_build
    steps:
      - uses: actions/checkout@v2
      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

  packer_build:
    name: Packer AMI Build
    needs: packer_validate
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: WebappJarFile
          path: /home/runner/work/webapp/webapp/target/demo1-0.0.1-SNAPSHOT.jar

      - uses: actions/checkout@v2

      - name: Packer build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ami.pkr.hcl'
          command: build
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: us-west-2

