name: Run packer build on a template file

on:
  pull_request:
    branches:
      - main
jobs:
  package_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile

      - name: Test with Maven
        run: mvn test

      - name: Package with Maven
        run: |
          pwd
          ls
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
          pwd
          ls -al

      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: webapp-artifact
          path: staging

      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

      - name: Download jar file
        uses: actions/download-artifact@v2
        with:
          name: webapp-artifact

      - name: Packer build
        uses: hashicorp/packer-github-actions@master
        with:
          templateFile: 'ami.pkr.hcl'
          command: build
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: us-west-2